[package]
name = "gaia-csv-parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "gaia_csv_parser"
crate-type = ["cdylib"]

[dependencies]
csv = "1.3"
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
